### ISSUE TITLE
Is it possible to export Synthesia output as raw bytes

### ISSUE THREAD

**Issue by TAbdiukov** [jpmac26/nsfplay-synthesia#5]
I'm working on a related project and I'm wondering if it can be made possible for NSFPlay and / or Synthesia to export each instrument as raw byte sequences of pitch. 

Is it currently possible or is it possible to implement?

**Comment by CaptainSwag101** [comment]
I have no idea, I'm sorry. This is a years-old repo just to give folks an easier way to find the code for this modification of NSFPlay; it's not my code and I'm really not at all familiar with it. I am probably going to archive it to indicate that I'm not the maintainer or developer.

**Comment by TAbdiukov** [comment]
all good, thanks for the info! I think that https://github.com/bschlenk/pynsf is my best bet
